### PR TITLE
#159082313 Users should be able to comment on articles

### PR DESCRIPTION
**Pull request by RutaleIvanPaul**
#### What does this PR do?
It allows users to add comments to articles. Find the article by using the slug.
#### What are the relevant pivotal tracker stories?
#159082313

### CODE REVIEW

**Comment by AGMETEOR** [comment]
Rutale, the build failed. I think you have some errors in the code.

**Comment by AGMETEOR** [comment]
It has now passed. I don't know why it errored initially.

**Comment by RutaleIvanPaul** [comment]
Did you add anything to the requirements? The PR is passing.

**Comment by RutaleIvanPaul** [comment]
The build was actually passing. It had encountered errors with installing requirements. I restarted it and it passed

**Pull request merged**
